{
  "hash": "4706595b1fb427c829ec73351252d27d",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Bat cunnilingus and spurious results\"\ndescription: \"Critique of work on bat cunnilingus\"\nauthor:\n  - name: Andy Field\n    url: https://profandyfield.com\ndate: 02 04 2013\ncategories: [R, Statistics, Robust methods, Research critique] # self-defined categories\ncitation: \n  url: https://profandyfield.com/posts/2013_04_02_bats/ \nimage: bat.jpg\ndraft: false # setting this to `true` will prevent your post from appearing on your listing page until you're ready!\nbibliography: references.yaml\n---\n\n\nThanks to my brother I became aware of an article about bat cunnilingus today [@maruthupandian2013]. My brother, knowing how entertained I had been by a bat felating itself at Disney on my honeymoon, decided that this would be just the sort of article that I'd like. Knowing the kind of examples I put in my textbooks I suspect his email is the first of many. Anyway, this article suggests that male bats engage in cunnilingus with females. Female bats, that is. They have videos to prove it. Male bats like cunnilingus so much that they don't just use it as foreplay, but they get stuck in afterwards as well. The article has two main findings:\n\n> The more that males (bats) engage in cunnilingus, the longer the duration of intercourse, $r$ = .91 (see their Figure 1).\n\nThey tested this with a Pearson *r*, based on 8 observations (although each observation was the average of several data points I think – it's not entirely clear how the authors came about these averages). They conclude that this behaviour may be due to sperm competition in that males sort of 'clean out' the area before they procreate. They argue that the longer intercourse duration supports this argument because longer duration = greater chance of paternity.\n\n> The more that males engage in pre-intercourse cunnilingus, the less they engage in post-intercourse cunnilingus, *r* = –.79 (see their Figure 2).\n\nThey again tested this with a Pearson *r*, based on 8 observations. They conclude *\"… the negative relationship between the duration of pre- and post-copulatory cunnilingus suggests the possibility of sperm competition. Thus, the male removes the sperm of competitors but apparently not its own – lick for longer before but less after copulation, if paternity uncertainty is high.\"*\n\nThere are several leaps of faith in their conclusions. Does longer duration necessarily imply greater chance of paternity? Also, if sperm competition is at the root of all of this then I'm not sure post coital cunilingus is really ever an adaptive strategy: consuming your own sperm hardly seems like the best method of impregnating your mate. Yes, I'm still talking about bats here, what you choose to do in your own free time is none of my business.\n\nEnough about Cunnilingus, what about Statistics?\n\nAnyway, I want to make a statistical point, not an evolutionary one. It struck me when looking at this article that finding 2 is probably spurious. Figure 2 looks very much like two outliers are making a relationship out of nothing. With only 8 observations they are likely to have a large impact. With 8 observations it is, of course, hard to say what's an outlier and what isn't; however, the figure was like a bat tongue to my brain: my juices were flowing. Fortunately, with so few observations we can approximate the data from the two figures. I emphasises that these are quick estimates of values based on the graphs and a ruler. We have three variables estimated from the paper: pre (pre-intercourse cunnilingus), post (post-intercourse cunnilingus), duration (duration of intercourse). We're going to use R, if you don't know how to use it then some imbecile called Andy Field has written a book on it that you could look at [@field2012; @fielddsr22025].\n\n\nLet's load some packages that will be useful (if you don't have them installed then install them) and input these approximate scores as shown below. They are displayed in @tbl-data.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(WRS2) #wilcox robust functions\nlibrary(correlation)\nlibrary(boot)\nlibrary(tidyverse)\n\nbat <- tibble(\n  pre = c(46, 50, 51, 52, 53, 53.5, 55, 59),\n  post = c(162, 140, 150, 140, 142, 138, 152, 122),\n  duration = c(14.4, 14.4, 14.9, 15.5, 15.4, 15.2, 15.3, 16.4)\n)\n```\n:::\n\n::: {#tbl-data .cell tbl-cap='Approximation of data from Maruthupandian & Marimuthu (2013)'}\n::: {.cell-output-display}\n\n\n|  pre| post| duration|\n|----:|----:|--------:|\n| 46.0|  162|     14.4|\n| 50.0|  140|     14.4|\n| 51.0|  150|     14.9|\n| 52.0|  140|     15.5|\n| 53.0|  142|     15.4|\n| 53.5|  138|     15.2|\n| 55.0|  152|     15.3|\n| 59.0|  122|     16.4|\n\n\n:::\n:::\n\n\n\nNow lets replicate Figures 1 (see @fig-mm131) and 2 (see @fig-mm132) from the paper. As you can see the figures – more or less – replicate their data.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data = bat, aes(x = pre, y = duration)) + \n  geom_point() +\n  stat_smooth(method = \"lm\") +\n  coord_cartesian(ylim = c(13, 18), xlim = c(44, 60)) +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![Replica of Maruthupandian & Marimuthu (2013) Figure 1](index_files/figure-html/fig-mm131-1.png){#fig-mm131 width=672}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data = bat, aes(x = pre, y = post)) + \n  geom_point() +\n  stat_smooth(method = \"lm\") +\n  coord_cartesian(ylim = c(85, 200), xlim = c(44, 60)) +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![Replica of Maruthupandian & Marimuthu (2013) Figure 2](index_files/figure-html/fig-mm132-1.png){#fig-mm132 width=672}\n:::\n:::\n\n\n\n\nOK, let's replicate their correlation coefficient estimates by executing:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncorrelation(bat, p_adjust = \"none\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# Correlation Matrix (pearson-method)\n\nParameter1 | Parameter2 |     r |         95% CI |  t(6) |       p\n------------------------------------------------------------------\npre        |       post | -0.78 | [-0.96, -0.17] | -3.05 | 0.023* \npre        |   duration |  0.91 | [ 0.56,  0.98] |  5.30 | 0.002**\npost       |   duration | -0.75 | [-0.95, -0.10] | -2.79 | 0.032* \n\np-value adjustment method: none\nObservations: 8\n```\n\n\n:::\n:::\n\n\nSo, we replicate the pre-intercourse cunnilingus (Pre) – duration correlation of .91 exactly (*p*= .002), and we more or less get the right value for the pre-post correlation: we get r = –.78 (*p* = .023) instead of -.79, but we're within rounding error. So, it looks like our estimates of the raw data from the Figures in the article aren't far off the real values at all. Just goes to show how useful graphs in papers can be for extracting the raw data. If I'm right and the data in Figure 2 are affected by the first and last case, we'd expect something different to happen if we calculate the correlation based on ranked scores (i.e. Spearman's rho). Let's try it: \n\n\n::: {.cell}\n\n```{.r .cell-code}\ncorrelation(bat, method = \"spearman\", p_adjust = \"none\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# Correlation Matrix (spearman-method)\n\nParameter1 | Parameter2 |   rho |        95% CI |      S |      p\n-----------------------------------------------------------------\npre        |       post | -0.50 | [-0.90, 0.34] | 126.25 | 0.204 \npre        |   duration |  0.78 | [ 0.14, 0.96] |  18.61 | 0.023*\npost       |   duration | -0.51 | [-0.90, 0.32] | 127.01 | 0.195 \n\np-value adjustment method: none\nObservations: 8\n```\n\n\n:::\n:::\n\n\nThe Pre-duration correlation has dropped from .91 to .78 (*p* = .023) but it's still very strong. However, the pre-post correlation has changed fairly dramatically from -.79 to *r* = –.50 (*p* = .204) and is now not significant (although I wouldn't want to read to much into that with an *n* = 8). What about if we try a robust correlation such as the percentile bend correlation described by @wilcox2017\n\n\n::: {.cell}\n\n```{.r .cell-code}\npbcor(bat$pre, bat$post)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCall:\npbcor(x = bat$pre, y = bat$post)\n\nRobust correlation coefficient: -0.3687\nTest statistic: -0.9714\np-value: 0.36884 \n```\n\n\n:::\n\n```{.r .cell-code}\npbcor(bat$pre, bat$duration)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCall:\npbcor(x = bat$pre, y = bat$duration)\n\nRobust correlation coefficient: 0.8522\nTest statistic: 3.9896\np-value: 0.0072 \n```\n\n\n:::\n:::\n\n\n\nThe pre post correlation has changed dramatically from -.79 to *r* = –.37 (*p* = .369) and is now not significant (again I wouldn't want to read to much into that with an *n* = 8, but it is now a much smaller effect than they're reporting in the paper). The pre-duration correlation fares much better: it is still very strong and significant, *r* = .85 (*p* = .007). We could also try to estimate the population value of these two relationships by computing a robust confidence interval using bootstrapping. We'll stick with Pearson *r* seeing as that's the estimate that they used in the paper but you could try this with the other measures if you like.\n\n\nIn essence then, the true relationship between pre- and post-intercourse cunnilingus duration lies somewhere between about –1 and 0.6. In other words, it could be anything really, including zero. \n\n\n::: {.cell}\n\n```{.r .cell-code}\nbootr <-function(data, i){ \n  cor(data[i, 1], data[i, 2])\n  } \n\nbootprepost <-boot(bat[1:2], bootr, 2000)\nboot.ci(bootprepost) \n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nBOOTSTRAP CONFIDENCE INTERVAL CALCULATIONS\nBased on 2000 bootstrap replicates\n\nCALL : \nboot.ci(boot.out = bootprepost)\n\nIntervals : \nLevel      Normal              Basic         \n95%   (-1.5951, -0.1754 )   (-2.0871, -0.5666 )  \n\nLevel     Percentile            BCa          \n95%   (-0.9927,  0.5278 )   (-0.9922,  0.5809 )  \nCalculations and Intervals on Original Scale\n```\n\n\n:::\n:::\n\n\nFor the relationship between pre-intercourse bat cunnilingus and intercourse duration the true relationship is somewhere between r= .5 and .98. In other words, it's likely to be – at the very worst – a strong and positive association.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbootpreduration <- boot(bat[c(1, 3)], bootr, 2000)\nboot.ci(bootpreduration)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nBOOTSTRAP CONFIDENCE INTERVAL CALCULATIONS\nBased on 2000 bootstrap replicates\n\nCALL : \nboot.ci(boot.out = bootpreduration)\n\nIntervals : \nLevel      Normal              Basic         \n95%   ( 0.6699,  1.1990 )   ( 0.8323,  1.2201 )  \n\nLevel     Percentile            BCa          \n95%   ( 0.5954,  0.9832 )   ( 0.5306,  0.9805 )  \nCalculations and Intervals on Original Scale\n```\n\n\n:::\n:::\n\n\n\n:::{.callout-note}\nWhat does this tell us? Well, I'm primarily interested in using this as a demonstration of why it's important to look at your data and to employ robust tests. I'm not trying to knock the research. Of course, in the process I am, inevitably, sort of knocking it. So, I think there are three messages here:\n\n1. Their first finding that the more that males (bats) engage in cunnilingus, the longer the duration of intercourse is very solid. The population value could be less than the estimate they report, but it could very well be that large too. At the very worst it is still a strong association.\n2. The less good news is that finding 2 (that the more that males engage in pre-intercourse cunnilingus, the less they engage in post-intercourse cunnilingus) is probably wrong. The best case scenario is that the finding is real but the authors have overestimated it. The worst case scenario is that the population effect is in the opposite direction to what the authors report, and there is, of course, a mid ground that there is simply no effect at all in the population (or one so small as to be not remotely important).\n3. It's also worth pointing out that the two extreme cases that have created this spurious result may in themselves be highly interesting observations. There may be important reasons why individual bats engage in unusually long or short bouts of cunnilingus (either pre or post intercourse) and finding out what factors affect this will be an interesting thing that the authors should follow up.\n:::\n\n::: refs\n:::\n\n",
    "supporting": [
      "index_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}